spring.application.name=vetclinic
spring.datasource.url=jdbc:mysql://localhost:3306/pawthway_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true